#!/bin/sh

### CONFIG

# GitLab URL
gitlab_url=git.atosphere.info
# secret GitLab API token
token=
# complete URL to the GitLab API

USER=ato

### FUNCTIONS

TOK="?private_token=$token"
api_url=http://$gitlab_url/api/v3

function gitlab_usage
{
	echo "usage : git gitlab [command]

   new [name]      create a new repository
   delete [name]   delete the repository
   list            list all the repositories on the GitLab server
   -h              show this help" 1>&2 && exit 1
}


### MAIN

cmd=$1

test -z $cmd && gitlab_usage
case "$cmd" in
	"new")
		repo=$2
		test -z $repo && gitlab_usage
		if curl -H "Content-Type:application/json" $api_url/projects$TOK -d "{ \"name\":\"$repo\" }" 2>/dev/null | jq -e .id 1>/dev/null;
		then
			echo "Repo created !"
		else
			echo "Repo already exists, or an error happened"
		fi
	;;
	"list")
		curl -X GET $api_url/projects$TOK 2>/dev/null | jq --raw-output 'map(.id, .name)'
	;;
	"delete")
		name=$2
		test -z $name && gitlab_usage
		id=$( curl -X GET $api_url/projects$TOK 2>/dev/null | jq '.[] | select(.name=="'$name'") | .id'; )
		test -z $id && echo "This repo does not exists." && exit 1
		curl -X DELETE $api_url/projects/$id$TOK 1>/dev/null 2>/dev/null && echo "Repo deleted"
	;;
	"clone")
		name=$2
		test -z $name && gitlab_usage
		echo $USER
		git clone ssh://git@$gitlab_url:$USER/$name
	;;
	"-h")
		gitlab_usage
	;;
esac
