#!/bin/bash

test -z $1 && return 1
test -z $2 && return 1
delim_s=$2
delim_e=$3
test -z $3 && delim_e=$2

word_size=$(echo -n $1 | wc -c | tr -d ' ')
com_size=$(echo -n $delim_e | wc -c | tr -d ' ')
b=$((40 - $com_size - $word_size / 2)) # branch size
start=$(gen "$delim_s$b-")
end=$(gen "$b-$delim_e")
echo "$start $1 $end"
